### ISSUE TITLE
eksempel på issue

### ISSUE THREAD

**Issue by ovi-medcom** [medcomdk/ehmi#13]
@kml930 
du kan skrive et issue på denne måde og lave et link til det sted i dokumentationen, du adresserer: [index-side på bla bla](https://github.com/medcomdk/ehmi/commit/b1c51fe6fc69b293d6daf7e73a76cb71ffb02595) 
Du kan sætte en assignee på, mig (@ovi-medcom) for eksempel ;-), og en label

**Comment by kml930** [comment]
Spændende! Jeg giver det et skud 👍
