### ISSUE TITLE
Ændringer til "About afsnittet" som er placeret nederst på hver github page

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#14]
Hej Ole!
Mit første forsøg på oprettelse af issue :-) 

Det vedrører detalje ændringer til About-afsnittet, som er placeret nederst på hver github page. Jeg kan ikke finde denne "index side" med about-afsnittet i branchen, så jeg kan rette deri. Kan du guide mig dertil? 

/K

**Comment by ovi-medcom** [comment]
Godt gået :-)
du kan finde det her: [default.html](https://github.com/medcomdk/ehmi/blob/main/docs/_layouts/default.html)
gå ned til linie 150
