### ISSUE TITLE
Spørgsmål til github-siden "Specificering af sikkerhed ifm meddelelsesflow i EHMI Core"

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#15]
Github side: Specificering af sikkerhed ifm meddelelsesflow i EHMI Core (https://medcomdk.github.io/ehmi/assets/documents/security/security-specification-of-ehmi-core.html#generelle-sikkerhedsm%C3%A6ssige-definitioner-for-komponenter-i-forsendelsesk%C3%A6den)

1. Illustration øverst på siden virker for stor – se eksempelvis illustration på fanen "EHMI Core", som har en mere tilpas størrelse. Jeg ved dog ikke, hvordan man gør illustrationen mindre. Derudover er illustration på dansk.

2. Indholdsfortegnelse: Bør nummereringen af overskrifterne ikke fjernes fra indholdsfortegnelsen? Tallene går nemlig ikke igen i selve overskrifterne nede på siden. 

3. Spørgsmål til oversættelse i afsnittet "Generelt omkring sikkerhed for komponenter (eng: General information about security for components in EHMI): 
Der skal ske en stærk autentifikation af brugere (svarende til NIST niveau 3-4 eller NSIS niveau ”betydeligt”)
1. Der skal foretages adgangskontrol baseret på nationalt standardiseret information (attributter)
2. Samtykke/frabedelse og **behandlingsrelation** (hvilken **engelsk** oversættelse for behandlingsrelation? **Treatment relationship**?) skal tjekkes op mod den nationale samtykkeservice og den nationale **behandlingsrelationsservice** (hvilken **engelsk** oversættelse? **national treatment relationship service**?)
3. Oplysninger om sundhedspersoners adgang til persondata skal kunne ses af borgeren (hvilken **engelsk** oversættelse? citizen/patient?) via MinLog

4. **Engelsk** oversættelse af **Målbilledet**?

5. **Engelsk** oversættelse af sætningen "Implementering af **signering af forsendelse**"? Fx Implementation of **signing of delivery**

6. **Engelsk** oversættelse af "Integritetssikring og fortrolighedssikring"? Fx **Integrity protection and confidentiality protection**?

7. **Engelsk** oversættelse af "Implementering af signering af meddelelse"? Fx Implementation of **message signing**?

8. **Engelsk** oversættelse af "Verifikation af signering ved modtagelse"? Fx Verification of **signature upon receipt**?

**Comment by ovi-medcom** [comment]
2. Indholdsfortegnelse: Bør nummereringen af overskrifterne ikke fjernes fra indholdsfortegnelsen? Tallene går nemlig ikke igen i selve overskrifterne nede på siden. OVI: JA

**Comment by ovi-medcom** [comment]
1. Illustration øverst på siden virker for stor – se eksempelvis illustration på fanen "EHMI Core", som har en mere tilpas størrelse. Jeg ved dog ikke, hvordan man gør illustrationen mindre. Derudover er illustration på dansk. 

**_OVI: Link til præsentation, hvor illustrationerne er fra: [EHMI Pixi - nyt design](https://medcomdk.sharepoint.com/:p:/s/Produktionspilotforkommunaleprvesvar/EawTiDP7cU5Lp7AHhZXvoUwBuH9q7Tf4O5joFELyxKXUKA?e=UDD7zO) Du må gerne kopiere og oversætte slidene som nye slides. Jeg har tidligere gemt slides som billeder, der efterfølgende kan reduceres i størrelse, så de passer_**

**Comment by ovi-medcom** [comment]
3. Spørgsmål til oversættelse i afsnittet "Generelt omkring sikkerhed for komponenter (eng: General information about security for components in EHMI):
Der skal ske en stærk autentifikation af brugere (svarende til NIST niveau 3-4 eller NSIS niveau ”betydeligt”)

**_OVI: A strong authentication of users must take place (equivalent to NIST level 3-4 or NSIS level "substantial")_**

**Comment by ovi-medcom** [comment]
4. Der skal foretages adgangskontrol baseret på nationalt standardiseret information (attributter)

**_OVI: Access control must be carried out based on nationally standardized information (attributes)_**

**Comment by ovi-medcom** [comment]
> 6. Oplysninger om sundhedspersoners adgang til persondata skal kunne ses af borgeren (hvilken **engelsk** oversættelse? citizen/patient?) via MinLog

_**OVI: begge ;-)**_

**Comment by ovi-medcom** [comment]
> 7. **Engelsk** oversættelse af **Målbilledet**?

_**OVI: Architectural Vision**_

**Comment by kml930** [comment]
> 1. Illustration øverst på siden virker for stor – se eksempelvis illustration på fanen "EHMI Core", som har en mere tilpas størrelse. Jeg ved dog ikke, hvordan man gør illustrationen mindre. Derudover er illustration på dansk.
> 
> **_OVI: Link til præsentation, hvor illustrationerne er fra: [EHMI Pixi - nyt design](https://medcomdk.sharepoint.com/:p:/s/Produktionspilotforkommunaleprvesvar/EawTiDP7cU5Lp7AHhZXvoUwBuH9q7Tf4O5joFELyxKXUKA?e=UDD7zO) Du må gerne kopiere og oversætte slidene som nye slides. Jeg har tidligere gemt slides som billeder, der efterfølgende kan reduceres i størrelse, så de passer_**

Super, mange tak for hjælpen. Jeg har givet mit bedste bud på engelsk oversættelse af illustrationen og indsat den på siden. Jeg kan dog ikke vurdere, om den er mindre end den originale illustration..
