### ISSUE TITLE
Link virker ikke

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#19]
### Specificering af sikkerhed ifm. centrale EHMI-services
Sti: docs/assets/documents/security/security-specification-of-ehmi-eds.md

Følgende link virker ikke (linje 49):  [Security architecture EHMI support services v01 (opens in new window)](https://github.com/medcomdk/ehmi/blob/karina-review/docs/assets/documents/security/media/Sikkerhedsarkitektur%20EHMI%20st%C3%B8tteservices%20v01.pdf)

**Comment by ovi-medcom** [comment]
corrected in karina-review branch :-)
