### ISSUE TITLE
Hjælp til links

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#22]
På EHMI Core siden: https://github.com/medcomdk/ehmi/blob/karina-review/docs/assets/documents/ecore/index.md

Linje 71 og 72: 
Det drejer sig om følgende links, som jeg ikke kan få til at virke, når jeg prøver at kode det... Forstår ikke hvorfor. 

[EHMI Profile of SBDH (ehmiSBDH)](/ehmiSBDH/index.md) --> dvs. koden bagved er (/ehmiSBDH/index.md)
[EHMI Profile of Service Metadata Publisher (ehmiSMP)](/ehmiSMP/index.md) --> dvs. koden bagved er (/ehmiSMP/index.md)

Jeg kan kun få linket til at virke, hvis jeg sætter hele stien ind. 
[EHMI Profile of SBDH (ehmiSBDH)](https://medcomdk.github.io/ehmi/assets/documents/ecore/ehmiSBDH/) --> dvs. koden bagved er (https://medcomdk.github.io/ehmi/assets/documents/ecore/ehmiSBDH/)
[EHMI Profile of Service Metadata Publisher (ehmiSMP)](https://medcomdk.github.io/ehmi/assets/documents/ecore/ehmiSMP/) --> dvs. koden bagved er (https://medcomdk.github.io/ehmi/assets/documents/ecore/ehmiSMP/)

Jeg kan nemlig se, at du/I kan linke til andre steder ved blot at indsætte de sidste titler i linket (som de første to eksempler i indeværende issue). Jeg vil bare ikke gøre det forkert, så du må meget gerne sige til, hvis det er en forkert måde at henvise til en side på github på ved at sætte hele stien ind (som i de to sidste eksempler).

**Comment by ovi-medcom** [comment]
Det er som sådan ikke forkert at sætte hele stien ind, men i mit udviklingsværktøj hjælper den med at gøre stierne kortere. Det er ikke noget problem med det du gør :-)
