### ISSUE TITLE
Opdatering af link

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#23]
EHMI Core: https://github.com/medcomdk/ehmi/edit/karina-review/docs/assets/documents/ecore/index.md

Linje 123: 
DS Metadata | DDS Metadata-v1.0.0 | [To be updated] --> Link skal opdateres

**Comment by ovi-medcom** [comment]
Der skal stå: https://svn.medcom.dk/svn/releases/Standarder/IHE/DK_profil_metadata/XDS%20Metadata%20for%20Document%20Sharing.%20Danish%20profile%20v.1.0.0.pdf
