### ISSUE TITLE
Link virker ikke

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#24]
Det nederste link "SMP hos Digital Europe (EU)" på siden: https://medcomdk.github.io/ehmi/assets/documents/ecore/ehmiSMP/ virker ikke.

**Comment by ovi-medcom** [comment]
De har slettet siden :-(
Det skal skiftes ud med https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/SMP+specifications
