### ISSUE TITLE
Hvilken version af projektets tidsplans-illustration skal benyttes

### ISSUE THREAD

**Issue by kml930** [medcomdk/ehmi#27]
Jeg er i gang med at oversætte slides fra: [EHMI Pixi - nyt design](https://medcomdk.sharepoint.com/:p:/s/Produktionspilotforkommunaleprvesvar/EawTiDP7cU5Lp7AHhZXvoUwBuH9q7Tf4O5joFELyxKXUKA?e=UDD7zO) Men slide 6-7 vedr. projektets tidsplan stemmer ikke overens med den illustration, der er brugt på selve github siden for [produktionspiloten](https://medcomdk.github.io/ehmi/assets/documents/production-pilot/)

Hvilken illustration skal jeg gå med? Den der er på hjemmesiden, eller den der er i powerpoint pixi? :-)

**Comment by ovi-medcom** [comment]
Kirsten har den rigtige tidsplan :-)
